name: Build, Test and Deploy NestJS API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: back
        run: npm install

      - name: Build Application
        working-directory: back
        run: npm run build

      - name: Run Tests
        working-directory: back
        run: npm run test