name: Build, Test and Deploy Angular Webapp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: front
        run: npm install

      - name: Build Application
        working-directory: front
        run: npm run build

      - name: Run Tests
        working-directory: front
        run: npm run test:ci

      - name: Generate Documentation
        working-directory: front
        run: npm run docs

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package in NPM
        working-directory: front
        run: |
          git config --global user.email "strackzdesign@gmail.com"
          git config --global user.name "strackzdev"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/strackzdev/y_integration_deploiement.git
          npm version patch -m "Upgrade to %s [skip ci]"
          git commit -am "NPM Version Increment"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push new NPM version to GIT
        working-directory: front
        run: |
          git push origin HEAD:master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: front/dist/integration_deploiement_personal_front/browser

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2